
services:
  apache:
    image: isaiaspy/php-apache-base  # Usando imagem oficial do PHP com Apache
    build: .  # Constrói o container usando o Dockerfile local
    container_name: php-apache
    volumes:
      - ./public:/var/www/html  # Código da aplicação PHP
      - ./php.ini:/usr/local/etc/php/php.ini  # Configuração personalizada do PHP
    ports:
      - "8000:80"  # Porta local 8000 acessa o Apache (porta 80) no container
    depends_on:
      - db  # Aguarda o banco de dados iniciar

  db:
    image: mysql:5.7  # Usando imagem oficial do MySQL 5.7
    container_name: mysql-db
    restart: always  # Reinicia automaticamente se algo falhar
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do usuário root do MySQL
      MYSQL_DATABASE: meu_banco  # Nome do banco de dados a ser criado
      MYSQL_USER: user  # Nome de usuário adicional
      MYSQL_PASSWORD: senha  # Senha do usuário adicional
    ports:
      - "3307:3306"
  # Porta local 3307 conectando ao MySQL
    volumes:
      - dbdata:/var/lib/mysql  # Volume para persistência de dados

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  # Interface web para o MySQL
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Acesse phpMyAdmin via http://localhost:8081
    environment:
      PMA_HOST: db  # Conecta ao serviço "db" (MySQL)
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:  # Volume nomeado para manter os dados do banco mesmo após reiniciar containers
